### ISSUE TITLE
Are intervals exclusive or inclusive ranges?

### ISSUE THREAD

**Issue by hazelutf8** [electronjoe/intervals-general#4]
While playing with this nice an simple interval representation library with inclusive interval ranges, the comments seem to imply inclusive ranges are supported, but the code seems to enforce exclusive range construction?

Inclusive range suggested:
https://github.com/electronjoe/intervals-general/blame/master/README.md#L13

Exclusive range enforced:
https://github.com/electronjoe/intervals-general/blob/f68b4ceff03be443e9025faf5f3ba2a2d084eba8/src/bound_pair.rs#L39

Is this wanted behavior?

**Comment by electronjoe** [comment]
Apologies @hazelutf8 ! I lack notifications and did not anticipate users! Hah!

So the BoundPair you are pointing at is only used if you are constructing an Interval with Bounds not equal (hence the check here that they are not equal).  E.g. [a, b) or (a,b] or [a,b] etc where a != b.  If you want a=b (a singleton effectively) then you will not construct a BoundPair as the Interval variant you want is Interval::Singleton(val). See [Here](https://github.com/electronjoe/intervals-general/blob/f68b4ceff03be443e9025faf5f3ba2a2d084eba8/src/interval.rs#L33).

So sorry it took a half a year to reply!
